Lcam-515-adding integration test
ministryofjustice/laa-crime-evidence pull request #23
Opened 2023-03-27 11:29 UTC by loganathanMOJ

## What

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-515)

Describe what you did and why.

Adding integration test for Crime Evidence endpoints.

Before you ask people to review this PR:

- [ ] Tests should be passing: `./gradlew test`
- [ ] Github should not be reporting conflicts; you should have recently run `git rebase main`.
- [ ] Avoid mixing whitespace changes with code changes in the same commit. These make diffs harder to read and conflicts more likely.
- [ ] You should have looked at the diff against main and ensured that nothing unexpected is included in your changes.
- [ ] You should have checked that the commit messages say why the change was made.

2023-03-28 09:28 UTC, loganathanMOJ commented on crime-evidence/src/main/java/uk/gov/justice/laa/crime/evidence/config/ResourceServerConfiguration.java
> +                .cors().and().csrf().disable()
Fixed now

2023-03-28 21:21 UTC, AafAnsari requested changes

2023-03-28 21:21 UTC, AafAnsari commented on crime-evidence/src/main/java/uk/gov/justice/laa/crime/evidence/exception/CrimeEvidenceExceptionHandler.java
> +    }
ValidationException is not used anywhere in the code, so it's not required here

2023-03-28 21:21 UTC, AafAnsari commented on crime-evidence/src/main/java/uk/gov/justice/laa/crime/evidence/exception/CrimeEvidenceExceptionHandler.java
> +    public ResponseEntity<ErrorDTO> handleCCPDataException(CrimeEvidenceDataException ex) {
`handleCCPDataException` can be renamed to `handleCrimeEvidenceDataException`

2023-03-28 21:21 UTC, AafAnsari commented on crime-evidence/src/main/java/uk/gov/justice/laa/crime/evidence/exception/CrimeEvidenceExceptionHandler.java
> +        log.error("CCPDataException: ", ex);
`CCPDataException` can be renamed to `CrimeEvidenceDataException`

2023-03-28 21:21 UTC, AafAnsari commented on crime-evidence/src/main/java/uk/gov/justice/laa/crime/evidence/exception/ValidationException.java
> +
This exception class is not called. Can be removed

2023-03-29 06:18 UTC, AafAnsari approved these changes

2023-03-29 06:18 UTC, merged